# Vectorization

Vectorized code is a programming technique that performs mathematical operations on multiple components of a vector at once. Vectorized code can make code faster, more concise, and easier to maintain. It can also be more portable and clean. Vectorize code can improve performance when run in GPUs instead of CPUs.

## Parameters and features

$b$ is a number.

$ \overrightarrow w = [w_1, w_2, w_3] $

$ \overrightarrow x = [x_1, x_2, x_3] $

These can be represented in Python using Numpy:

In [17]:
import numpy as np

b = 4
w = np.array([ 1.0, 2.5, -3.3 ])
x = np.array([ 10, 20, 30 ])

## Running model without vectorization (Naive approach)

$ f _ {\overrightarrow w, b} ( \overrightarrow x ) = \sum\limits_{j = 1} ^ n w_j x_j + b$

In [18]:
n = len(w)
f = 0

for j in range (0, n):

    f = f + w[j] * x[j]

f = f + b

print(f'Prediction: {f * 1000}')

Prediction: -35000.0


## Running model with vectorization (Optimized approach)

$ f_{ \overrightarrow w, b } ( \overrightarrow x ) = \overrightarrow w \bullet \overrightarrow x + b$

In [19]:
f = 0
f = np.dot(w, x) + b

print(f'Prediction: {f * 1000}')

Prediction: -35000.0


# Numpy data creation routines



In [20]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}\n")
a = np.zeros((4,3));             print(f"np.zeros(4,3) :  \na =\n {a},\na shape = {a.shape}, a data type = {a.dtype}\n")
a = np.random.random_sample((4,3)); print(f"np.random.random_sample(4, 3): \na =\n {a},\n a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64

np.zeros(4,3) :  
a =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]],
a shape = (4, 3), a data type = float64

np.random.random_sample(4, 3): 
a =
 [[0.16910717 0.70956267 0.57192451]
 [0.05067146 0.277952   0.57040874]
 [0.06018187 0.78221684 0.65866885]
 [0.4013866  0.26671725 0.64104181]],
 a shape = (4, 3), a data type = float64


In [21]:
# Some data creation routines do not take a shape tuple:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.66602284 0.97338041 0.79684553 0.05995491], a shape = (4,), a data type = float64


In [22]:
# Values can be specified manually.
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


# Numpy operations on vectors

In [23]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9


# Vector Slicing

In [24]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


# Single vector operations

In [25]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


### Vector Vector element-wise operations

In [26]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

# Both arrays have to be of the same size.
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print(e)

Binary operators work element wise: [0 0 6 8]
operands could not be broadcast together with shapes (4,) (2,) 


### Scalar Vector operations

In [27]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]
